### ISSUE TITLE
Blueprint Error running the sample app

### ISSUE THREAD

**Issue by mbch** [talkpython/htmx-python-course#1]
Tried to run the app from the ch4_starter_video_collector folder. I'm using anaconda, had to install pydantic but when I tried to run the app I got the error that Blueprint does not have a get method. I replace get with route in all 3 view files - and not the app is running fine. Just as a hint for others stumbling at this point. Excited to move this app to htmx. Thx for the course.

**Comment by mikeckennedy** [comment]
Glad you’re enjoying the course! This is because you’re running Flask 1.11
or older. The course is designed for Flask 2.0+.

This usually happens because people are using conda rather than pip which
for reasons I don’t understand, is it is usually 6m to 1yr (!) behind on
web framework releases.

You can use Flask 1 if you exchange get/post for route instead like you did
here.

Cheers,
Michael

Best,
Michael

Sent via Superhuman iOS ***@***.***>

**Comment by mbch** [comment]
Switched to Flask 2.0 - problem solved. Thanks for this super fast support!!!!
