### ISSUE TITLE
sys.gettrace() is not being used anymore 

### ISSUE THREAD

**Issue by ar-qun** [talkpython/htmx-python-course#8]
Hi there,

While going through the course, I have noticed that the debugging mode in Pycharm doesn't activate the debugging mode in Flask anymore. However, if I replace the code below

https://github.com/talkpython/htmx-python-course/blob/d9cc19e8d898787cbbfa4b820339708a8350f923/code/ch4_app/ch4_final_video_collector/app.py#L50

with

```python
    being_debugged = sys.monitoring.get_tool(sys.monitoring.DEBUGGER_ID) is not None
```

It now works again.

If maintainers approve of this change I will prepare a PR :) I can also keep it backward compatible.

What do you think?

**Comment by mikeckennedy** [comment]
Hey, I appreciate you looking into this. I'm running the latest PyCharm available, 2023.3.4, and it works as is.

<img width="602" alt="Screenshot 2024-03-11 at 4 16 51 PM" src="https://github.com/talkpython/htmx-python-course/assets/2035561/90644d8b-2319-45a7-bdbc-6c3e480af7ac">

And for printing it out when running directly (because there are no break points without the debugger):

```python
being_debugged = sys.gettrace() is not None
print(f'{being_debugged=}')
```

Output:

```
being_debugged=False
```

What am I missing here?

**Comment by ar-qun** [comment]
Probably the Python version then.

After looking into it, it seems that this [1] issue is present in the newest Pycharm versions when using with Python 3.12 due to new monitoring API [2]. I just confirmed that `sys.gettrace()` works fine in 3.11.

[1] https://stackoverflow.com/questions/77624964/check-if-program-runs-in-debug-mode-in-pycharm-2023
[2] https://blog.jetbrains.com/pycharm/2024/01/new-low-impact-monitoring-api-in-python-3-12/

**Comment by mikeckennedy** [comment]
I see what I was missing! On Python 3.11 it works fine, but 3.12 it doesn't. I'll get it fixed across the course code samples, thanks!

**Comment by mikeckennedy** [comment]
Thanks again @ar-qun Should be fixed now.
